//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regulus.Remote.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regulus.Remote.CodeAnalysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Type names should be all uppercase. 的當地語系化字串。
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type name &apos;{0}&apos; contains lowercase letters 的當地語系化字串。
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type name contains lowercase letters 的當地語系化字串。
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nameing 的當地語系化字串。
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No support for generic type &apos;{0}&apos;. 的當地語系化字串。
        /// </summary>
        internal static string MessageReturnRuleNoFixed {
            get {
                return ResourceManager.GetString("MessageReturnRuleNoFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The number of parameters cannot exceed 5. 的當地語系化字串。
        /// </summary>
        internal static string rr0004_description {
            get {
                return ResourceManager.GetString("rr0004-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &apos;{0}&apos; is too many parameters. 的當地語系化字串。
        /// </summary>
        internal static string rr0004_message {
            get {
                return ResourceManager.GetString("rr0004-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error params. 的當地語系化字串。
        /// </summary>
        internal static string rr0004_title {
            get {
                return ResourceManager.GetString("rr0004-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setter is not supported. 的當地語系化字串。
        /// </summary>
        internal static string rr0006_description {
            get {
                return ResourceManager.GetString("rr0006-description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setter is not supported. 的當地語系化字串。
        /// </summary>
        internal static string rr0006_message {
            get {
                return ResourceManager.GetString("rr0006-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error property. 的當地語系化字串。
        /// </summary>
        internal static string rr0006_title {
            get {
                return ResourceManager.GetString("rr0006-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The return value does not support types other than Regulus.Remote.Value or System.Void. 的當地語系化字串。
        /// </summary>
        internal static string RRE1Description {
            get {
                return ResourceManager.GetString("RRE1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No support type &apos;{0}&apos;. 的當地語系化字串。
        /// </summary>
        internal static string RRE1Message {
            get {
                return ResourceManager.GetString("RRE1Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error return value. 的當地語系化字串。
        /// </summary>
        internal static string RRE1Title {
            get {
                return ResourceManager.GetString("RRE1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The parameter must not be an interface type. 的當地語系化字串。
        /// </summary>
        internal static string RRE2Description {
            get {
                return ResourceManager.GetString("RRE2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parameter &apos;{0}&apos; must not be an interface type. 的當地語系化字串。
        /// </summary>
        internal static string RRE2Message {
            get {
                return ResourceManager.GetString("RRE2Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error params. 的當地語系化字串。
        /// </summary>
        internal static string RRE2Title {
            get {
                return ResourceManager.GetString("RRE2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The parameter must not be an generic type. 的當地語系化字串。
        /// </summary>
        internal static string RRE3Description {
            get {
                return ResourceManager.GetString("RRE3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parameter &apos;{0}&apos; must not be an generic type. 的當地語系化字串。
        /// </summary>
        internal static string RRE3Message {
            get {
                return ResourceManager.GetString("RRE3Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error params. 的當地語系化字串。
        /// </summary>
        internal static string RRE3Title {
            get {
                return ResourceManager.GetString("RRE3Title", resourceCulture);
            }
        }
    }
}
